# version: '3.8'
services:
  frontend:
    build:
      context: ./trinity
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./trinity:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://database:27017/mydb

  # database:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - db_data:/data/db

database:
  image: postgres:latest
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: mydb
  ports:
    - "5432:5432"
  volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:
