# Dockerfile.prod pour le backend
FROM node:16

# Dossier de travail
WORKDIR /app

# Copier uniquement les fichiers package.json pour installer les dépendances de production
COPY package*.json ./

# Installer uniquement les dépendances de production
RUN npm install --only=production

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 5000

# Lancer l'application en mode production
CMD ["node", "src/index.js"]
