# Dockerfile.dev pour le backend
FROM node:16

# Dossier de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installer les dépendances (inclut les dépendances de dev comme nodemon)
RUN npm install

# Copier le code source
COPY . .

# Exposer le port
EXPOSE 5000

# Démarrer le serveur avec nodemon pour rechargement automatique
CMD ["npx", "nodemon", "src/index.js"]
