# Utiliser une image Node.js légère
FROM node:18-alpine as build

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances et construire l'application
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# Utiliser une image NGINX pour servir les fichiers statiques
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port NGINX
EXPOSE 80

# Pas de CMD car NGINX est configuré par défaut
