# Dockerfile.dev pour le frontend
FROM node:16

# Dossier de travail
WORKDIR /app

# Copier les fichiers package.json pour installer les dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port pour le serveur de développement
EXPOSE 3000

# Lancer le serveur de développement de React
CMD ["npm", "start"]
