# Utiliser une image Node.js légère
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier de package et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port utilisé par l'application React
EXPOSE 3000

# Démarrer l'application en mode développement
CMD ["npm", "start"]

