# Étape 1 : Utiliser une image de Node.js comme image de base
FROM node:18-alpine

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Étape 3 : Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier tous les fichiers de l'application dans le conteneur
COPY . .

# Étape 6 : Exposer le port sur lequel votre application écoute
EXPOSE 3000

# Étape 7 : Définir la commande pour démarrer l'application
CMD ["npm", "start"]
