FROM node:18

# Définir le répertoire de travail
WORKDIR /api

# Mettre à jour npm à la dernière version stable
RUN npm install 

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./

# Installer les dépendances en nettoyant le cache
RUN npm cache clean --force && npm install

# Copier le reste du projet dans l'image
COPY . .

# Exposer le port utilisé par l'application
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm"]
